In [1]:
import numpy as np

In [2]:
array_1d = np.arange(1,20)

In [3]:
array_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [4]:
array_1d[0:5]=100

In [5]:
array_1d

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19])

In [6]:
array_2d = np.ones((4,4))

In [7]:
array_2d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
array_2d[0]=300

In [9]:
array_2d

array([[300., 300., 300., 300.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.]])

In [10]:
array_2d+300

array([[600., 600., 600., 600.],
       [301., 301., 301., 301.],
       [301., 301., 301., 301.],
       [301., 301., 301., 301.]])

In [12]:
a =  np.array([[0.0,1.0,2.0],[10.0,20.0,30.0],[100.0,200.0,300.0]])
b = np.array([1000.0,2000.0,3000.0])

In [14]:
a

array([[  0.,   1.,   2.],
       [ 10.,  20.,  30.],
       [100., 200., 300.]])

In [15]:
b

array([1000., 2000., 3000.])

In [16]:
a+b

array([[1000., 2001., 3002.],
       [1010., 2020., 3030.],
       [1100., 2200., 3300.]])

In [20]:
print('First Array : ')
print(a)
print('\n')

First Array : 
[[  0.   1.   2.]
 [ 10.  20.  30.]
 [100. 200. 300.]]




In [19]:
print('Second Array : ')
print(b)
print('\n')

Second Array : 
[1000. 2000. 3000.]




In [21]:
print('First + Second: ')
print(a+b)

First + Second: 
[[1000. 2001. 3002.]
 [1010. 2020. 3030.]
 [1100. 2200. 3300.]]
