In [3]:
import numpy as np

In [3]:
np.arange(100)  #similar to range() in python

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [4]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [4]:
np.arange(1,10,1, dtype='float')

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [5]:
np.linspace(1,2,100)

array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
       1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
       1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
       1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
       1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
       1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
       1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
       1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
       1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
       1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
       1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
       1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
       1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
       1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
       1.70707071, 1.71717172, 1.72727273, 1.73737374, 1.74747

In [7]:
my_linspace = np.linspace(1,2,100, retstep=True)
my_linspace

(array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
        1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
        1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
        1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
        1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
        1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
        1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
        1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
        1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
        1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
        1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
        1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
        1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
        1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
        1.70707071, 1.71717172, 1.72727273, 1.73

In [11]:
np.linspace(9,29,20, retstep=True)

(array([ 9.        , 10.05263158, 11.10526316, 12.15789474, 13.21052632,
        14.26315789, 15.31578947, 16.36842105, 17.42105263, 18.47368421,
        19.52631579, 20.57894737, 21.63157895, 22.68421053, 23.73684211,
        24.78947368, 25.84210526, 26.89473684, 27.94736842, 29.        ]),
 1.0526315789473684)