In [1]:
import numpy as np

In [10]:
arr=np.arange(1,11)

In [11]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr2 = np.arange(100,110)
arr2

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [12]:
arr + arr2

array([101, 103, 105, 107, 109, 111, 113, 115, 117, 119])

In [16]:
arr2 - arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [14]:
arr*arr2

array([ 100,  202,  306,  412,  520,  630,  742,  856,  972, 1090])

In [15]:
arr2/arr

array([100.        ,  50.5       ,  34.        ,  25.75      ,
        20.8       ,  17.5       ,  15.14285714,  13.375     ,
        12.        ,  10.9       ])

In [17]:
arr2**arr

array([       100,      10201,    1061208,  112550881, -718372864,
         65844273,  515833472, -250506143,  -18087936, -827800951])

In [18]:
1/arr2

array([0.01      , 0.00990099, 0.00980392, 0.00970874, 0.00961538,
       0.00952381, 0.00943396, 0.00934579, 0.00925926, 0.00917431])

In [19]:
0/arr2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
arr/0

C:\Users\User\AppData\Local\Temp\ipykernel_2412\4291252909.py:1: RuntimeWarning: divide by zero encountered in divide
  arr/0


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [21]:
2*arr


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [22]:
1+arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
arr2-109

array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0])