In [4]:
import numpy as np

In [5]:
array_1d = np.array([2,4,6,8,10,12,14,16,18,20])
array_1d

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
type(array_1d)

numpy.ndarray

In [7]:
array_1d[0]

2

In [10]:
array_1d[3:-2]

array([ 8, 10, 12, 14, 16])

In [11]:
array_1d[3:7]

array([ 8, 10, 12, 14])

In [12]:
array_1d[:7]

array([ 2,  4,  6,  8, 10, 12, 14])

In [13]:
array_1d[3:]

array([ 8, 10, 12, 14, 16, 18, 20])

In [14]:
array_1d[::]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [16]:
array_1d


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [19]:
array_1d[0:10:3]

array([ 2,  8, 14, 20])

In [20]:
array_1d[::2]

array([ 2,  6, 10, 14, 18])

In [21]:
array_1d[-2]

18

In [22]:
array_1d[1:-2]

array([ 4,  6,  8, 10, 12, 14, 16])

In [23]:
#assign a new value to a certain index
array_1d[9]=22
array_1d

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 22])

In [24]:
array_1d

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 22])