In [1]:
import numpy as np

In [2]:
array_2d = np.arange(24)
array_2d.shape = (6,4)
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [3]:
array_2d[2]

array([ 8,  9, 10, 11])

In [4]:
array_2d[-4]

array([ 8,  9, 10, 11])

In [5]:
array_2d[5][2]

22

In [6]:
row = 5
col = 2
array_2d[row][col]

22

In [7]:
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [8]:
#2d array slicing
#array_2d[:2,:2].shape gives (2,2) -- 4 elements for top left corner
#[row:row,column:column][From 0 row to 1 row,from 0 col to 1 col]
#array_2d[0:2,0:2] is same as array_2d[:2,:2]

In [9]:
array_2d[:2,:2]

array([[0, 1],
       [4, 5]])

In [10]:
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [11]:
array_2d[[0,2,3]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
array_2d[:,[2]]

array([[ 2],
       [ 6],
       [10],
       [14],
       [18],
       [22]])

In [13]:
array_2d[[3,0,1]]

array([[12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])