In [1]:
import numpy as np

In [2]:
array_arange=np.arange(16)
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [3]:
array_arange.ndim  #dimension koto ta bole dey

1

In [4]:
array_arange.shape

(16,)

In [5]:
array_arange.itemsize

4

In [6]:
array_arange.size

16

In [7]:
array_arange.nbytes

64

In [8]:
array_arange.dtype

dtype('int32')

In [9]:
array_arange.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
array_arange.shape=(4,4)

In [13]:
array_arange

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
array_arange.reshape(16,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [15]:
array_arange.reshape(16,1).shape

(16, 1)