In [1]:
import numpy as np

In [2]:
arr=np.arange(1,11)

In [3]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [5]:
np.max(arr)

10

In [6]:
np.min(arr)

1

In [7]:
arr.max()

10

In [9]:
arr.min()

1

In [10]:
np.max(arr),np.min(arr)

(10, 1)

In [11]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [12]:
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153])

In [13]:
np.tan(arr)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619,  0.87144798, -6.79971146, -0.45231566,  0.64836083])

In [15]:
np.arcsin(arr)

C:\Users\User\AppData\Local\Temp\ipykernel_13332\1580827672.py:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(arr)


array([1.57079633,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan])

In [18]:
arr2 = np.arange(1,49)

In [26]:
array_2d=arr2.reshape(4,12)
array_2d

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48]])

In [31]:
array_2d.reshape(4,12).shape

(4, 12)

In [30]:
array_2d.sum()

1176

In [28]:
array_2d.sum(axis=0) #rowwise

array([ 76,  80,  84,  88,  92,  96, 100, 104, 108, 112, 116, 120])

In [27]:
array_2d.sum(axis=1) #colwise

array([ 78, 222, 366, 510])

In [32]:
array_2d.std() #standard_deviation

13.853399101544236