In [1]:
import numpy as np

In [2]:
np.__version__

'1.24.3'

In [4]:
arr = np.array([0, 1, 2])
print(arr + 2)

[2 3 4]


In [6]:
my_list = np.array([-1,0,1])
print(type(my_list))

<class 'numpy.ndarray'>


In [7]:
list = [0,1,2]
list*2

[0, 1, 2, 0, 1, 2]

In [8]:
arr = np.array([0,1,2])
arr*2

array([0, 2, 4])

# Simillarities between numPy array and lists

In [ ]:
#Storing Data
#Can be indexed
#Mutable
#Slicing Options

# Differences

In [ ]:
#1.List::Different datatypes & Array: Similar datatypes

#2.list = [0,1,2]
#list*2
#output:[0, 1, 2, 0, 1, 2]


#arr = np.array([0,1,2])
#arr*2
#output:array([0, 2, 4])

In [4]:
myarr = np.array([3,5,4,"a"])
myarr

array(['3', '5', '4', 'a'], dtype='<U11')

In [6]:
mylist = [3,4,5,"a"]
mylist

[3, 4, 5, 'a']

In [7]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones((11))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.ones((3,2),dtype="int32")

array([[1, 1],
       [1, 1],
       [1, 1]])

In [12]:
np.full((3,3),99)

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [18]:
np.random.rand(8,4) #0--1

array([[0.5741071 , 0.54146376, 0.55934603, 0.12024795],
       [0.42531385, 0.26843689, 0.16244064, 0.51376252],
       [0.69043804, 0.743409  , 0.77668196, 0.83201471],
       [0.81336127, 0.0582146 , 0.23751577, 0.69786041],
       [0.79570154, 0.56381619, 0.30446116, 0.5265016 ],
       [0.05171443, 0.53884113, 0.15727852, 0.29565445],
       [0.07703414, 0.87966201, 0.32042238, 0.01287106],
       [0.52945588, 0.70382412, 0.01317914, 0.19825209]])

In [15]:
np.random.randint(1,100,18) #int_value

array([97, 96, 35, 71, 64, 32, 81, 48, 10, 66, 75, 23,  7, 84, 78, 20, 89,
       32])

In [16]:
np.random.randint(-4,8,size=(3,3))

array([[1, 6, 1],
       [1, 1, 0],
       [0, 1, 1]])

In [19]:
np.random.randn(20)

array([-2.69678908, -0.24388795,  0.80746961,  0.84629619,  0.09587668,
        0.29390393, -1.16955812, -1.04701001,  0.26661813,  0.75979221,
       -1.34066494,  0.1337941 ,  0.10643973, -0.89561419, -0.06752385,
       -0.2627427 ,  0.18393261, -1.32361569, -0.7645304 ,  0.80278771])

In [2]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [3]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])