In [1]:
import pandas as pd
import numpy as np


In [2]:
index='r1 r2 r3 r4 r5 r6 r7 r8 r9 r10'.split()
columns ='c1 c2 c3 c4 c5 c6 c7 c8 c9 c10'.split()

In [3]:
index

['r1', 'r2', 'r3', 'r4', 'r5', 'r6', 'r7', 'r8', 'r9', 'r10']

In [4]:
columns

['c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9', 'c10']

In [5]:
array_2D=np.arange(0,100)

In [6]:
array_2D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [7]:
array_2D=array_2D.reshape(10,10)

In [8]:
array_2D

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [9]:
#dataframe

In [10]:
df = pd.DataFrame(data=array_2D,index=index,columns=columns)

In [11]:
df

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r1    0   1   2   3   4   5   6   7   8    9
r2   10  11  12  13  14  15  16  17  18   19
r3   20  21  22  23  24  25  26  27  28   29
r4   30  31  32  33  34  35  36  37  38   39
r5   40  41  42  43  44  45  46  47  48   49
r6   50  51  52  53  54  55  56  57  58   59
r7   60  61  62  63  64  65  66  67  68   69
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99

In [12]:
df['c2']

r1      1
r2     11
r3     21
r4     31
r5     41
r6     51
r7     61
r8     71
r9     81
r10    91
Name: c2, dtype: int32

In [13]:
df[['c4','c10']]

c4  c10
r1    3    9
r2   13   19
r3   23   29
r4   33   39
r5   43   49
r6   53   59
r7   63   69
r8   73   79
r9   83   89
r10  93   99

In [14]:
type(df['c10'])

pandas.core.series.Series

In [15]:
df['r1']

KeyError: 'r1'

In [ ]:
type(df[['c2']])

In [ ]:
df['c1','c2']

In [ ]:
df[['c1','c10','c3']]

In [ ]:
df.c5

In [ ]:
type(df.c5)

In [ ]:
#Adding New Column

In [ ]:
df['c11']=df['c1']+df['c2']

In [ ]:
df

In [ ]:
df['c11']='A'

In [ ]:
df

In [ ]:
df['c12']='X'

In [ ]:
df

In [ ]:
new_col=[1,2,34,5,6,7,8,9,0,12]

df.insert(loc=3,
          column='c13',
          value=new_col 
)

In [ ]:
df

In [ ]:
#drop column

In [ ]:
df.drop('c10',axis=1) #col-delete--axis=1;row-delete--axis=0

In [ ]:
df.drop('r10',axis=0,inplace=True)

In [ ]:
df

In [ ]:
df.loc[['r5']] #row ke alada kore

In [ ]:
df.iloc[[3]]

In [ ]:
df.loc[['r1','r2','r7']]

In [ ]:
df.loc['r2','c1']

In [ ]:
df.loc[['r1','r2'],['c1','c2']]

In [ ]:
df.loc[['r2','r7'],['c3','c7']]

In [ ]:
df > 5

In [ ]:
df

In [17]:
bool_mask = df%3 == 0
bool_mask

c1     c2     c3     c4     c5     c6     c7     c8     c9    c10
r1    True  False  False   True  False  False   True  False  False   True
r2   False  False   True  False  False   True  False  False   True  False
r3   False   True  False  False   True  False  False   True  False  False
r4    True  False  False   True  False  False   True  False  False   True
r5   False  False   True  False  False   True  False  False   True  False
r6   False   True  False  False   True  False  False   True  False  False
r7    True  False  False   True  False  False   True  False  False   True
r8   False  False   True  False  False   True  False  False   True  False
r9   False   True  False  False   True  False  False   True  False  False
r10   True  False  False   True  False  False   True  False  False   True

In [18]:
df[bool_mask]

c1    c2    c3    c4    c5    c6    c7    c8    c9   c10
r1    0.0   NaN   NaN   3.0   NaN   NaN   6.0   NaN   NaN   9.0
r2    NaN   NaN  12.0   NaN   NaN  15.0   NaN   NaN  18.0   NaN
r3    NaN  21.0   NaN   NaN  24.0   NaN   NaN  27.0   NaN   NaN
r4   30.0   NaN   NaN  33.0   NaN   NaN  36.0   NaN   NaN  39.0
r5    NaN   NaN  42.0   NaN   NaN  45.0   NaN   NaN  48.0   NaN
r6    NaN  51.0   NaN   NaN  54.0   NaN   NaN  57.0   NaN   NaN
r7   60.0   NaN   NaN  63.0   NaN   NaN  66.0   NaN   NaN  69.0
r8    NaN   NaN  72.0   NaN   NaN  75.0   NaN   NaN  78.0   NaN
r9    NaN  81.0   NaN   NaN  84.0   NaN   NaN  87.0   NaN   NaN
r10  90.0   NaN   NaN  93.0   NaN   NaN  96.0   NaN   NaN  99.0

In [19]:
df[df['c1']>11]

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r3   20  21  22  23  24  25  26  27  28   29
r4   30  31  32  33  34  35  36  37  38   39
r5   40  41  42  43  44  45  46  47  48   49
r6   50  51  52  53  54  55  56  57  58   59
r7   60  61  62  63  64  65  66  67  68   69
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99

In [20]:
df[df['c1']>11][['c3','c10']]

c3  c10
r3   22   29
r4   32   39
r5   42   49
r6   52   59
r7   62   69
r8   72   79
r9   82   89
r10  92   99

In [21]:
result = df[df['c1']>11]
result

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r3   20  21  22  23  24  25  26  27  28   29
r4   30  31  32  33  34  35  36  37  38   39
r5   40  41  42  43  44  45  46  47  48   49
r6   50  51  52  53  54  55  56  57  58   59
r7   60  61  62  63  64  65  66  67  68   69
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99

In [22]:
df[df['c1']>11]['c3','c10'] #series e ekta column hoy,duita column hoy na

KeyError: ('c3', 'c10')

In [23]:
df[df['c1']>11]['c3']

r3     22
r4     32
r5     42
r6     52
r7     62
r8     72
r9     82
r10    92
Name: c3, dtype: int32

In [25]:
result = df[df['c1']==70]
result

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r8  70  71  72  73  74  75  76  77  78   79

In [26]:
df

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r1    0   1   2   3   4   5   6   7   8    9
r2   10  11  12  13  14  15  16  17  18   19
r3   20  21  22  23  24  25  26  27  28   29
r4   30  31  32  33  34  35  36  37  38   39
r5   40  41  42  43  44  45  46  47  48   49
r6   50  51  52  53  54  55  56  57  58   59
r7   60  61  62  63  64  65  66  67  68   69
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99

In [29]:
res = df[(df['c1']>60) & (df['c2']>80)]
res

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99

In [30]:
res = df[(df['c1']>60) | (df['c2']>80)]
res

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99

In [32]:
df.reset_index(inplace=True)
df

level_0 index  c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
0        0    r1   0   1   2   3   4   5   6   7   8    9
1        1    r2  10  11  12  13  14  15  16  17  18   19
2        2    r3  20  21  22  23  24  25  26  27  28   29
3        3    r4  30  31  32  33  34  35  36  37  38   39
4        4    r5  40  41  42  43  44  45  46  47  48   49
5        5    r6  50  51  52  53  54  55  56  57  58   59
6        6    r7  60  61  62  63  64  65  66  67  68   69
7        7    r8  70  71  72  73  74  75  76  77  78   79
8        8    r9  80  81  82  83  84  85  86  87  88   89
9        9   r10  90  91  92  93  94  95  96  97  98   99

In [33]:
df.set_index('c2',inplace=True)
df

level_0 index  c1  c3  c4  c5  c6  c7  c8  c9  c10
c2                                                    
1         0    r1   0   2   3   4   5   6   7   8    9
11        1    r2  10  12  13  14  15  16  17  18   19
21        2    r3  20  22  23  24  25  26  27  28   29
31        3    r4  30  32  33  34  35  36  37  38   39
41        4    r5  40  42  43  44  45  46  47  48   49
51        5    r6  50  52  53  54  55  56  57  58   59
61        6    r7  60  62  63  64  65  66  67  68   69
71        7    r8  70  72  73  74  75  76  77  78   79
81        8    r9  80  82  83  84  85  86  87  88   89
91        9   r10  90  92  93  94  95  96  97  98   99

In [34]:
df

level_0 index  c1  c3  c4  c5  c6  c7  c8  c9  c10
c2                                                    
1         0    r1   0   2   3   4   5   6   7   8    9
11        1    r2  10  12  13  14  15  16  17  18   19
21        2    r3  20  22  23  24  25  26  27  28   29
31        3    r4  30  32  33  34  35  36  37  38   39
41        4    r5  40  42  43  44  45  46  47  48   49
51        5    r6  50  52  53  54  55  56  57  58   59
61        6    r7  60  62  63  64  65  66  67  68   69
71        7    r8  70  72  73  74  75  76  77  78   79
81        8    r9  80  82  83  84  85  86  87  88   89
91        9   r10  90  92  93  94  95  96  97  98   99

In [35]:
array_2D

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [36]:
columns

['c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9', 'c10']

In [37]:
df = pd.DataFrame(data=array_2D,index=index,columns=columns)

In [38]:
df

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r1    0   1   2   3   4   5   6   7   8    9
r2   10  11  12  13  14  15  16  17  18   19
r3   20  21  22  23  24  25  26  27  28   29
r4   30  31  32  33  34  35  36  37  38   39
r5   40  41  42  43  44  45  46  47  48   49
r6   50  51  52  53  54  55  56  57  58   59
r7   60  61  62  63  64  65  66  67  68   69
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99

In [39]:
abc='a b c d e f g h i j'.split()
df['newind']=abc
df

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10 newind
r1    0   1   2   3   4   5   6   7   8    9      a
r2   10  11  12  13  14  15  16  17  18   19      b
r3   20  21  22  23  24  25  26  27  28   29      c
r4   30  31  32  33  34  35  36  37  38   39      d
r5   40  41  42  43  44  45  46  47  48   49      e
r6   50  51  52  53  54  55  56  57  58   59      f
r7   60  61  62  63  64  65  66  67  68   69      g
r8   70  71  72  73  74  75  76  77  78   79      h
r9   80  81  82  83  84  85  86  87  88   89      i
r10  90  91  92  93  94  95  96  97  98   99      j

In [40]:
df.set_index('newind',inplace=True)
df

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
newind                                         
a        0   1   2   3   4   5   6   7   8    9
b       10  11  12  13  14  15  16  17  18   19
c       20  21  22  23  24  25  26  27  28   29
d       30  31  32  33  34  35  36  37  38   39
e       40  41  42  43  44  45  46  47  48   49
f       50  51  52  53  54  55  56  57  58   59
g       60  61  62  63  64  65  66  67  68   69
h       70  71  72  73  74  75  76  77  78   79
i       80  81  82  83  84  85  86  87  88   89
j       90  91  92  93  94  95  96  97  98   99

In [41]:
df.head() #1st 5 ta

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
newind                                         
a        0   1   2   3   4   5   6   7   8    9
b       10  11  12  13  14  15  16  17  18   19
c       20  21  22  23  24  25  26  27  28   29
d       30  31  32  33  34  35  36  37  38   39
e       40  41  42  43  44  45  46  47  48   49

In [42]:
df.tail() #last 5 ta

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
newind                                         
f       50  51  52  53  54  55  56  57  58   59
g       60  61  62  63  64  65  66  67  68   69
h       70  71  72  73  74  75  76  77  78   79
i       80  81  82  83  84  85  86  87  88   89
j       90  91  92  93  94  95  96  97  98   99

In [43]:
df.head(2)

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
newind                                         
a        0   1   2   3   4   5   6   7   8    9
b       10  11  12  13  14  15  16  17  18   19

In [44]:
df.tail(1)

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
newind                                         
j       90  91  92  93  94  95  96  97  98   99

In [46]:
df
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   c1      10 non-null     int32
 1   c2      10 non-null     int32
 2   c3      10 non-null     int32
 3   c4      10 non-null     int32
 4   c5      10 non-null     int32
 5   c6      10 non-null     int32
 6   c7      10 non-null     int32
 7   c8      10 non-null     int32
 8   c9      10 non-null     int32
 9   c10     10 non-null     int32
dtypes: int32(10)
memory usage: 480.0+ bytes


In [47]:
df 
df.describe()

c1         c2         c3         c4         c5         c6  \
count  10.000000  10.000000  10.000000  10.000000  10.000000  10.000000   
mean   45.000000  46.000000  47.000000  48.000000  49.000000  50.000000   
std    30.276504  30.276504  30.276504  30.276504  30.276504  30.276504   
min     0.000000   1.000000   2.000000   3.000000   4.000000   5.000000   
25%    22.500000  23.500000  24.500000  25.500000  26.500000  27.500000   
50%    45.000000  46.000000  47.000000  48.000000  49.000000  50.000000   
75%    67.500000  68.500000  69.500000  70.500000  71.500000  72.500000   
max    90.000000  91.000000  92.000000  93.000000  94.000000  95.000000   

              c7         c8         c9        c10  
count  10.000000  10.000000  10.000000  10.000000  
mean   51.000000  52.000000  53.000000  54.000000  
std    30.276504  30.276504  30.276504  30.276504  
min     6.000000   7.000000   8.000000   9.000000  
25%    28.500000  29.500000  30.500000  31.500000  
50%    51.000000  52.000000  53.000000  54.000000  
75%    73.500000  74.500000  75.500000  76.500000  
max    96.000000  97.000000  98.000000  99.000000