In [1]:
import numpy as np
import pandas as pd
data_dic = {'col_1':[1,2,3,4,5],
           'col_2':[111,222,333,111,555],
           'col_3':['alpha','bravo','charlie',np.nan,np.nan],
           }
df = pd.DataFrame(data_dic)
df

col_1  col_2    col_3
0      1    111    alpha
1      2    222    bravo
2      3    333  charlie
3      4    111      NaN
4      5    555      NaN

In [2]:
df

col_1  col_2    col_3
0      1    111    alpha
1      2    222    bravo
2      3    333  charlie
3      4    111      NaN
4      5    555      NaN

In [3]:
df['col_2'].unique()

array([111, 222, 333, 555], dtype=int64)

In [4]:
print(df['col_1'].unique())
print(df['col_2'].unique())
print(df['col_3'].unique())

[1 2 3 4 5]
[111 222 333 555]
['alpha' 'bravo' 'charlie' nan]


In [5]:
print(df['col_1'].nunique())
print(df['col_2'].nunique())
print(df['col_3'].nunique())

5
4
3


In [6]:
df

col_1  col_2    col_3
0      1    111    alpha
1      2    222    bravo
2      3    333  charlie
3      4    111      NaN
4      5    555      NaN

In [7]:
df['col_2'].value_counts()

col_2
111    2
222    1
333    1
555    1
Name: count, dtype: int64

In [8]:
df['col_2'].count()

5

In [9]:
df['col_3'].value_counts()

col_3
alpha      1
bravo      1
charlie    1
Name: count, dtype: int64

In [10]:
df

col_1  col_2    col_3
0      1    111    alpha
1      2    222    bravo
2      3    333  charlie
3      4    111      NaN
4      5    555      NaN

In [11]:
df.sort_values(by='col_2')

col_1  col_2    col_3
0      1    111    alpha
3      4    111      NaN
1      2    222    bravo
2      3    333  charlie
4      5    555      NaN

In [12]:
df.sort_values(by='col_2', ascending=False)

col_1  col_2    col_3
4      5    555      NaN
2      3    333  charlie
1      2    222    bravo
0      1    111    alpha
3      4    111      NaN

In [13]:
# Our customized function to calculate the squares 
def square(value):
    return value * value

In [14]:
df

col_1  col_2    col_3
0      1    111    alpha
1      2    222    bravo
2      3    333  charlie
3      4    111      NaN
4      5    555      NaN

In [15]:
square(3)

9

In [16]:
df['col_1'].apply(square)

0     1
1     4
2     9
3    16
4    25
Name: col_1, dtype: int64

In [17]:
df['col_1'].apply(lambda value:value*value)

0     1
1     4
2     9
3    16
4    25
Name: col_1, dtype: int64

In [19]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [20]:
df.columns

Index(['col_1', 'col_2', 'col_3'], dtype='object')

In [21]:
df

col_1  col_2    col_3
0      1    111    alpha
1      2    222    bravo
2      3    333  charlie
3      4    111      NaN
4      5    555      NaN

In [22]:
newdf = df.copy()
newdf

col_1  col_2    col_3
0      1    111    alpha
1      2    222    bravo
2      3    333  charlie
3      4    111      NaN
4      5    555      NaN

In [23]:
aa = df
aa

col_1  col_2    col_3
0      1    111    alpha
1      2    222    bravo
2      3    333  charlie
3      4    111      NaN
4      5    555      NaN

In [24]:
del newdf['col_1']

In [25]:
newdf

col_2    col_3
0    111    alpha
1    222    bravo
2    333  charlie
3    111      NaN
4    555      NaN

In [26]:
df

col_1  col_2    col_3
0      1    111    alpha
1      2    222    bravo
2      3    333  charlie
3      4    111      NaN
4      5    555      NaN

In [27]:
newdf['dd']=2

In [28]:
newdf

col_2    col_3  dd
0    111    alpha   2
1    222    bravo   2
2    333  charlie   2
3    111      NaN   2
4    555      NaN   2

In [29]:
newdf.insert(1, 'new-col2', [1,2,3,4,5])
newdf

col_2  new-col2    col_3  dd
0    111         1    alpha   2
1    222         2    bravo   2
2    333         3  charlie   2
3    111         4      NaN   2
4    555         5      NaN   2

In [30]:
newdf['dd'] = newdf['col_2'] * newdf['new-col2']

In [31]:
newdf['ddd']=11

In [32]:
newdf

col_2  new-col2    col_3    dd  ddd
0    111         1    alpha   111   11
1    222         2    bravo   444   11
2    333         3  charlie   999   11
3    111         4      NaN   444   11
4    555         5      NaN  2775   11